apiVersion: apps/v1
kind: Deployment
metadata:
  name: nutrition-app-deployment
  labels:
    app: nutrition-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nutrition-app
  template:
    metadata:
      labels:
        app: nutrition-app
    spec:
      containers:
        - name: streamlit-container
          image: mynsun/streamlitapp:latest
          ports:
            - containerPort: 8501
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key-secret
                  key: OPENAI_API_KEY
        - name: fastapi-container
          image: mynsun/fastapi-backend:latest
          ports:
            - containerPort: 3000
