apiVersion: v1
kind: Service
metadata:
  name: streamlitapp
  labels:
    app: nutrition-app
spec:
  type: NodePort
  selector:
    app: nutrition-app
  ports:
    - name: streamlit-http
      port: 8501
      targetPort: 8501
      nodePort: 30801
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: nutrition-app
spec:
  type: NodePort
  selector:
    app: nutrition-app
  ports:
    - name: fastapi-http
      port: 3000
      targetPort: 3000
      nodePort: 30802
      protocol: TCP
