apiVersion: v1
kind: Service
metadata:
  name: streamlitapp
  labels:
    run: streamlitapp
spec:
  type: NodePort  
  ports:
    - nodePort : 30801
      port: 8501       
      targetPort: 8501    
      protocol: TCP
      name: http
  selector:
    app: streamlitapp
  externalIPs:
    - 13.124.198.232