apiVersion: v1
kind: Service
metadata:
  name: food-detection-app
  labels:
    run: food-detection-app
spec:
  type: NodePort  
  ports:
    - nodePort : 30800   
      port: 8501       
      targetPort: 8501    
      protocol: TCP
      name: http
  selector:
    app: food-detection-app
  externalIPs:
    - 15.164.56.89